{% set name = "mirakuru" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mirakuru-{{ version }}.tar.gz
  sha256: 21192186a8680ea7567ca68170261df3785768b12962dd19fe8cccab15ad3441

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - psutil >=4.0.0
    - python >={{ python_min }}

test:
  imports:
    - mirakuru
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ClearcodeHQ/mirakuru
  summary: Process executor (not only) for tests.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
