{% set name = "mirakuru" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mirakuru-{{ version }}.tar.gz
  sha256: 5a60d641fa92c8bfcd383f6e52f7a0bf3f081da0467fc6e3e6a3f6b3e3e47a7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - psutil >=4.0.0
    - python >=3.7

test:
  imports:
    - mirakuru
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ClearcodeHQ/mirakuru
  summary: Process executor (not only) for tests.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
