{% set name = "mirakuru" %}
{% set version = "2.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mirakuru-{{ version }}.tar.gz
  sha256: 39b33f8fcdf13764a6cfe936e0feeead3902a161fec438df3be7cce98f7933c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - psutil >=4.0.0
    - python >=3.7

test:
  imports:
    - mirakuru
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ClearcodeHQ/mirakuru
  summary: Process executor (not only) for tests.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
